version: '3'
services:
  qinglong:
    image: ghcr.io/whyour/qinglong
    container_name: ql
    volumes:
      - ./data:/ql/data
    network_mode: bridge
    ports:
      - 5700:5700
    restart: unless-stopped
